# version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/riskdb

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - .:/frontend
      - /frontend/node_modules
    depends_on:
      - backend

  mongo:
    image: mongo
    container_name: mongo_container
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
